name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.201
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:
        PROJECT_FILE_PATH: src/WaterNSW.Crawling/Crawling.WaterNSW.csproj
        PACKAGE_NAME: CluedIn.Crawling.WaterNSW
        VERSION_REGEX: ‘^\s*<Version>(.*)<\/Version>\s*$’
        TAG_FORMAT: ‘*’
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
